Capstone/CS4760_Project/Models/Review.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CS4760_Project.Models
{
    public class Review
    {
        public int ReviewId { get; set; }
        public int GrantId { get; set; }
        public int CommitteeID { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Score { get; set; }

    }
}

Capstone/CS4760_Project/Pages/Colleges/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CS4760_Project.Data;
using CS4760_Project.Models;

namespace CS4760_Project.Pages.Colleges
{
    public class CreateModel : PageModel
    {
        private readonly CS4760_Project.Data.CS4760_ProjectContext _context;

        public CreateModel(CS4760_Project.Data.CS4760_ProjectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public College College { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.College.Add(College);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Capstone/CS4760_Project/Pages/Colleges/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CS4760_Project.Data;
using CS4760_Project.Models;

namespace CS4760_Project.Pages.Colleges
{
    public class DeleteModel : PageModel
    {
        private readonly CS4760_Project.Data.CS4760_ProjectContext _context;

        public DeleteModel(CS4760_Project.Data.CS4760_ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public College College { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var college = await _context.College.FirstOrDefaultAsync(m => m.CollegeId == id);

            if (college == null)
            {
                return NotFound();
            }
            else
            {
                College = college;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var college = await _context.College.FindAsync(id);
            if (college != null)
            {
                College = college;
                _context.College.Remove(College);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Capstone/CS4760_Project/Pages/Colleges/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CS4760_Project.Data;
using CS4760_Project.Models;

namespace CS4760_Project.Pages.Colleges
{
    public class DetailsModel : PageModel
    {
        private readonly CS4760_Project.Data.CS4760_ProjectContext _context;

        public DetailsModel(CS4760_Project.Data.CS4760_ProjectContext context)
        {
            _context = context;
        }

        public College College { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var college = await _context.College.FirstOrDefaultAsync(m => m.CollegeId == id);
            if (college == null)
            {
                return NotFound();
            }
            else
            {
                College = college;
            }
            return Page();
        }
    }
}

Capstone/CS4760_Project/Pages/Colleges/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CS4760_Project.Data;
using CS4760_Project.Models;

namespace CS4760_Project.Pages.Colleges
{
    public class EditModel : PageModel
    {
        private readonly CS4760_Project.Data.CS4760_ProjectContext _context;

        public EditModel(CS4760_Project.Data.CS4760_ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public College College { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var college =  await _context.College.FirstOrDefaultAsync(m => m.CollegeId == id);
            if (college == null)
            {
                return NotFound();
            }
            College = college;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(College).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CollegeExists(College.CollegeId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CollegeExists(int id)
        {
            return _context.College.Any(e => e.CollegeId == id);
        }
    }
}

Capstone/CS4760_Project/Pages/Committee/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CS4760_Project.Data;
using CS4760_Project.Models;

namespace CS4760_Project.Pages.Committee
{
    public class CreateModel : PageModel
    {
        private readonly CS4760_Project.Data.CS4760_ProjectContext _context;

        public CreateModel(CS4760_Project.Data.CS4760_ProjectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Models.Committee Committee { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Committee.Add(Committee);
            await _context.SaveChangesAsync();

            return RedirectToPage("./RSPG_Reviewers");
        }
    }
}

Capstone/CS4760_Project/Pages/Grants/Approve.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CS4760_Project.Data;
using CS4760_Project.Models;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Routing.Constraints;

using MimeKit;
using MailKit.Net.Smtp;
namespace CS4760_Project.Pages.Grants
{
    public class ApproveModel : PageModel
    {
        private readonly CS4760_ProjectContext _context;

        public ApproveModel(CS4760_ProjectContext context)
        {
            _context = context;
        }

        public Grant Grant { get; set; }

        public User GrantUser { get; set; }
        public User AuthenticatedUser { get; set; }
        [BindProperty]
        public List<FinancialRequest> PersonalResourceRequests { get; set; } = new List<FinancialRequest>();
        public List<FinancialRequest> EquipmentRequests { get; set; } = new List<FinancialRequest>();
        public List<FinancialRequest> TravelRequests { get; set; } = new List<FinancialRequest>();
        public List<FinancialRequest> OtherRequests { get; set; } = new List<FinancialRequest>();

        // Financial Request Amounts
        public decimal PersonalResourceRSPGAmount { get; set; }
        public decimal PersonalResourceAvailableAmount { get; set; }
        public decimal PersonalResourceTotalAmount { get; set; }
        public decimal EquipmentRSPGAmount { get; set; }
        public decimal EquipmentAvailableAmount { get; set; }
        public decimal EquipmentTotalAmount { get; set; }
        public decimal TravelRSPGAmount { get; set; }
        public decimal TravelAvailableAmount { get; set; }
        public decimal TravelTotalAmount { get; set; }
        public decimal OtherRSPGAmount { get; set; }
        public decimal OtherAvailableAmount { get; set; }
        public decimal OtherTotalAmount { get; set; }

        // Total Grant Amounts
        public decimal RSPGAmount { get; set; } = 0;
        public decimal AvailableAmount { get; set; } = 0;
        public decimal TotalAmount { get; set; } = 0;

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Grant = await _context.Grant.Where(c => c.GrantID == id).FirstOrDefaultAsync();

            PersonalResourceRequests = await _context.FinancialRequest
                .Where(fr => Grant.PersonalResourceRequestIds
                .Contains(fr.RequestId))
                .ToListAsync();

            EquipmentRequests = await _context.FinancialRequest
                .Where(fr => Grant.EquipmentRequestIds
                .Contains(fr.RequestId))
                .ToListAsync();

            TravelRequests = await _context.FinancialRequest
                .Where(fr => Grant.TravelRequestIds
                .Contains(fr.RequestId))
                .ToListAsync();

            OtherRequests = await _context.FinancialRequest
                .Where(fr => Grant.OtherRequestIds
                .Contains(fr.RequestId))
                .ToListAsync();

            // Create a list of lists for financial requests
            var allRequests = new List<List<FinancialRequest>>
            {
                PersonalResourceRequests,
                EquipmentRequests,
                TravelRequests,
                OtherRequests
            };

            CalculateTotals(allRequests);

            EquipmentTotalAmount = EquipmentRSPGAmount + EquipmentAvailableAmount;
            TravelTotalAmount = TravelRSPGAmount + TravelAvailableAmount;
            OtherTotalAmount = OtherRSPGAmount + OtherAvailableAmount;
            TotalAmount = RSPGAmount + AvailableAmount;

            return Page();
        }

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync(int id, bool approval)
        {
            Grant = await _context.Grant.Where(c => c.GrantID == id).FirstOrDefaultAsync();
            GrantUser = await _context.User.Where(c => c.Id == Grant.GrantUserID).FirstOrDefaultAsync();

            if (HttpContext.Session.GetString("UserData") != null)
            {
                AuthenticatedUser = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("UserData"));
                if (AuthenticatedUser != null)
                {
                    if (approval)
                    {
                        Grant.IsChairApproved = true;
                        Grant.IsAvailableForReview = true;
                        if (GrantUser.Email == "email")
                        {
                            Grant.IsChairApproved = false;
                            SendEmail(GrantUser.Email, "Grant Approval", "Your Grant was Approved");
                        }
                    }
                    else
                    {
                        Grant.IsChairRejected = true;
                        if (GrantUser.Email == "email")
                        {
                            Grant.IsChairRejected = false;
                            SendEmail(GrantUser.Email, "Grant Approval", "Your Grant was Rejected");
                        }
                    }
                }
            }


            await _context.SaveChangesAsync();

            return RedirectToPage("/Grants/ApproveList");
        }

        private void SendEmail(string to, string subject, string body)
        {
            var email = new MimeMessage();
            email.From.Add(MailboxAddress.Parse("email"));
            email.To.Add(MailboxAddress.Parse(to));
            email.Subject = subject;
            email.Body = new TextPart(MimeKit.Text.TextFormat.Html) { Text = body };
            using (var client = new SmtpClient())
            {
                client.Connect("smtp.gmail.com", 587, MailKit.Security.SecureSocketOptions.StartTls);
                client.Authenticate("email", "password");
                client.Send(email);
                client.Disconnect(true);
            }
        }
        private void CalculateTotals(List<List<FinancialRequest>> allRequests)
        {
            int index;

            RSPGAmount = 0;
            AvailableAmount = 0;

            foreach (var requests in allRequests)
            {
                index = allRequests.IndexOf(requests);

                foreach (var request in requests)
                {
                    if (request != null)
                    {
                        // Sum up the GrantAmount
                        RSPGAmount += request.GrantAmount; // Handle null GrantAmount as 0

                        // Sum up the available resources
                        AvailableAmount += request.Resource1Amount + request.Resource2Amount;

                        switch (index)
                        {
                            case 0:
                                PersonalResourceRSPGAmount += request.GrantAmount;
                                PersonalResourceAvailableAmount += request.Resource1Amount + request.Resource2Amount;
                                PersonalResourceTotalAmount += request.TotalWithTaxes;
                                break;

                            case 1:
                                EquipmentRSPGAmount += request.GrantAmount;
                                EquipmentAvailableAmount += request.Resource1Amount + request.Resource2Amount;
                                break;

                            case 2:
                                TravelRSPGAmount += request.GrantAmount;
                                TravelAvailableAmount += request.Resource1Amount + request.Resource2Amount;
                                break;

                            case 3:
                                PersonalResourceRSPGAmount += request.GrantAmount;
                                PersonalResourceAvailableAmount += request.Resource1Amount + request.Resource2Amount;
                                break;

                            default:
                                break;
                        }
                    }
                }
            }
        }

        public async Task<IActionResult> OnGetDownload(int id, string filename)
        {
            Grant = await _context.Grant.Where(c => c.GrantID == id).FirstOrDefaultAsync();

            if (string.IsNullOrEmpty(filename) || !Grant.FileNames.Contains(filename))
            {
                return NotFound();
            }

            var filePath = Path.Combine("wwwroot/Uploads/" + id + "_" + Grant.GrantTitle + "/" + id + "_" + filename);

            if (!System.IO.File.Exists(filePath))
            {
                return NotFound();
            }

            var fileBytes = System.IO.File.ReadAllBytes(filePath);
            return File(fileBytes, "application/octet-stream", filename);
        }
    }
}

Capstone/CS4760_Project/Pages/Grants/Approve.cshtml
@page
@model ApproveModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Review</h4>
<hr />
<div class="row">
    @foreach (var fileName in Model.Grant.FileNames)
    {
        <div class="col">
            <a asp-page-handler="Download" asp-route-id="@Model.Grant.GrantID" asp-route-filename="@fileName" style="width:75px"
               class="cancel">
                @fileName
            </a>
        </div>
    }
</div>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Grant.GrantTitle" class="control-label"></label>
    <input asp-for="Grant.GrantTitle" class="form-control" readonly="readonly" value="@Model.Grant.GrantTitle"/>
    <span asp-validation-for="Grant.GrantTitle" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Grant.GrantType" class="control-label"></label>
    <input asp-for="Grant.GrantType" class="form-control" readonly="readonly" value="@Model.Grant.GrantType" />
    <span asp-validation-for="Grant.GrantType" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Grant.GrantSubType" class="control-label"></label>
    <input asp-for="Grant.GrantSubType" class="form-control" readonly="readonly" value="@Model.Grant.GrantSubType" />
    <span asp-validation-for="Grant.GrantSubType" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Grant.PrincipalInvestigator" class="control-label"></label>
    <input asp-for="Grant.PrincipalInvestigator" class="form-control" readonly="readonly" value="@Model.Grant.PrincipalInvestigator" />
    <span asp-validation-for="Grant.PrincipalInvestigator" class="text-danger"></span>
</div>

<p></p>

<div>
    <p class="h5 mb-3">Financial Requests</p>

    <div class="row">
        <!-- Personal Resources Card -->
        <div class="col-md-6 mb-4">
            <a asp-page="/FinancialRequests/PersonalResourcesDetails" asp-route-id="@Model.Grant.GrantID" class="text-decoration-none">
                <div class="card shadow-sm h-100">
                    <div class="card-header bg-secondary text-white">
                        Personal Resources
                    </div>
                    <div class="card-body text-dark">
                        <p><strong>RSPG Amount:</strong> @Model.PersonalResourceRSPGAmount</p>
                        <p><strong>Available Amount:</strong> @Model.PersonalResourceAvailableAmount</p>
                        <p><strong>Total Amount:</strong> @Model.PersonalResourceTotalAmount</p>
                    </div>
                </div>
            </a>
        </div>

        <!-- Equipment Card -->
        <div class="col-md-6 mb-4">
            <a asp-page="/FinancialRequests/EquipmentDetails" asp-route-id="@Model.Grant.GrantID" class="text-decoration-none">
                <div class="card shadow-sm h-100">
                    <div class="card-header bg-secondary text-white">
                        Equipment
                    </div>
                    <div class="card-body text-dark">
                        <p><strong>RSPG Amount:</strong> @Model.EquipmentRSPGAmount</p>
                        <p><strong>Available Amount:</strong> @Model.EquipmentAvailableAmount</p>
                        <p><strong>Total Amount:</strong> @Model.EquipmentTotalAmount</p>
                    </div>
                </div>
            </a>
        </div>

        <!-- Travel Card -->
        <div class="col-md-6 mb-4">
            <a asp-page="/FinancialRequests/TravelDetails" asp-route-id="@Model.Grant.GrantID" class="text-decoration-none">
                <div class="card shadow-sm h-100">
                    <div class="card-header bg-secondary text-white">
                        Travel
                    </div>
                    <div class="card-body text-dark">
                        <p><strong>RSPG Amount:</strong> @Model.TravelRSPGAmount</p>
                        <p><strong>Available Amount:</strong> @Model.TravelAvailableAmount</p>
                        <p><strong>Total Amount:</strong> @Model.TravelTotalAmount</p>
                    </div>
                </div>
            </a>
        </div>

        <!-- Other Requests Card -->
        <div class="col-md-6 mb-4">
            <a asp-page="/FinancialRequests/OtherDetails" asp-route-id="@Model.Grant.GrantID" class="text-decoration-none">
                <div class="card shadow-sm h-100">
                    <div class="card-header bg-secondary text-white">
                        Other
                    </div>
                    <div class="card-body text-dark">
                        <p><strong>RSPG Amount:</strong> @Model.OtherRSPGAmount</p>
                        <p><strong>Available Amount:</strong> @Model.OtherAvailableAmount</p>
                        <p><strong>Total Amount:</strong> @Model.OtherTotalAmount</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

<div class="form-group">
    <label asp-for="Grant.RSPGAmount" class="control-label"></label>
    <input asp-for="Grant.RSPGAmount" class="form-control" readonly="readonly" value="@Model.Grant.RSPGAmount" />
    <span asp-validation-for="Grant.RSPGAmount" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Grant.AvailableAmount" class="control-label"></label>
    <input asp-for="Grant.AvailableAmount" class="form-control" readonly="readonly" value="@Model.Grant.AvailableAmount" />
    <span asp-validation-for="Grant.AvailableAmount" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Grant.TotalAmount" class="control-label"></label>
    <input asp-for="Grant.TotalAmount" class="form-control" readonly="readonly" value="@Model.Grant.TotalAmount" />
    <span asp-validation-for="Grant.TotalAmount" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Grant.Description" class="control-label"></label>
    <textarea name="Grant.Description" class="form-control" readonly="readonly">@Model.Grant.Description</textarea>
    <span asp-validation-for="Grant.Description" class="text-danger"></span>
</div>

<p></p>

    <div>
    <form method="post">
        <button asp-route-id="@Model.Grant.GrantID" asp-route-Approval="@true" class="btn greenButton">Approve</button>
        <button asp-route-id="@Model.Grant.GrantID" asp-route-Approval="@false" class="btn redButton" >Reject</button>
    </form>
    
    </div>
    <div>
        <p></p>
        <a asp-page="/Grants/ApproveList" class="btn button">Back to Approve List</a>
    </div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Capstone/CS4760_Project/Pages/Grants/ApproveList.cshtml
@page
@model CS4760_Project.Pages.Grants.ApproveListModel
@{
}


<h1>Approve</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Grants[0].GrantTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grants[0].GrantType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grants[0].GrantSubType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grants[0].PrincipalInvestigator)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Grants)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GrantTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GrantType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GrantSubType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrincipalInvestigator)
                </td>
                <td>
                    <a asp-page="/Grants/Approve" asp-route-id="@item.GrantID" class="btn purpleButton">Review</a>
                </td>
            </tr>
        }
    </tbody>
</table>


Capstone/CS4760_Project/Pages/Grants/Delete.cshtml
@page
@model CS4760_Project.Pages.Grants.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Grant</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.GrantTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.GrantTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.GrantType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.GrantType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.GrantSubType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.GrantSubType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.PrincipalInvestigator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.PrincipalInvestigator)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.RSPGAmount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.RSPGAmount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.AvailableAmount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.AvailableAmount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.TotalAmount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.TotalAmount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.PersonalResourceRequestIds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.PersonalResourceRequestIds)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.EquipmentRequestIds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.EquipmentRequestIds)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.TravelRequestIds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.TravelRequestIds)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grant.OtherRequestIds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grant.OtherRequestIds)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Grant.GrantID" />
        <input type="submit" value="Delete" class="btn redButton"/>
        <a asp-page="./Index" class="btn button">Back to List</a>
    </form>
</div>

Capstone/CS4760_Project/Pages/Grants/Index.cshtml
@page
@model CS4760_Project.Pages.Grants.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
    <p>
        <a asp-page="Create" class="btn purpleButton">Create New</a>
    </p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].GrantTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].GrantType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].GrantSubType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].PrincipalInvestigator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].RSPGAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].AvailableAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].TotalAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grant[0].IsAvailableForReview)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Grant) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GrantTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GrantType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GrantSubType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrincipalInvestigator)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RSPGAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.IsAvailableForReview)
            </td>
            <td>
                <div class="btn-group" role="group">
                    <a asp-page="./Edit" asp-route-id="@item.GrantID" class="btn greenButton btn-same-width">Edit</a>
                    <a asp-page="./Details" asp-route-id="@item.GrantID" class="btn yellowButton btn-same-width">Details</a>
                    <a asp-page="./Delete" asp-route-id="@item.GrantID" class="btn redButton btn-same-width">Delete</a>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>