Capstone/CS4760_Project/Pages/Admin/ARCC_Reviewers.cshtml.cs
using CS4760_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using CS4760_Project.Data;
using NuGet.Versioning;
using Microsoft.IdentityModel.Tokens;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;


namespace CS4760_Project.Pages.Admin
{
    public class ARCC_ReviewersModel : PageModel
    {
        private CS4760_Project.Data.CS4760_ProjectContext _context;
        public ARCC_ReviewersModel(CS4760_Project.Data.CS4760_ProjectContext context)
        {
            _context = context;
        }
        public User AuthenticatedUser { get; set; }
        public IList<User> User { get; set; } = default!;
        public IList<College> Colleges { get; set; } = default!;

        public IList<Department> Departments { get; set; } = default!;

        public IList<Models.Committee> Committees { get; set; } = default!;
        public List<dynamic> Users { get; set; } = new List<dynamic>();

        [BindProperty(SupportsGet = true)]
        public string FirstNameFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string LastNameFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string CollegeFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string DepartmentFilter { get; set; }

        [BindProperty]
        public Models.Committee Committee { get; set; }

        public IList<string> FilteredDepartments { get; set; } = new List<string>();
        public async Task OnGetAsync()
        {
            if (HttpContext.Session.GetString("UserData") != null)
            {
                AuthenticatedUser = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("UserData"));
            }
            
            Colleges = await _context.College.ToListAsync();

            var query = (from user in _context.User
                            join college in _context.College on user.CollegeId equals college.CollegeId
                            join department in _context.Department on user.DepartmentId equals department.DepartmentId
                            select new
                            {
                                IsAdmin = user.IsAdmin,
                                CommitteeId = user.CommitteeId,
                                Id = user.Id,
                                FirstName = user.FirstName,
                                LastName = user.LastName,
                                CollegeName = college.CollegeName,
                                DepartmentName = department.DepartmentName,
                                Committee = user.Committee,

                            });

            // Query Filters

            if (!string.IsNullOrWhiteSpace(FirstNameFilter))
            {
                query = query.Where(user => user.FirstName == FirstNameFilter);
            }

            if (!string.IsNullOrWhiteSpace(LastNameFilter))
            {
                query = query.Where(user => user.LastName == LastNameFilter);
            }

            if (!string.IsNullOrWhiteSpace(CollegeFilter))
            {
                query = query.Where(college => college.CollegeName == CollegeFilter);
                var departments = (from department in _context.Department
                                    where department.College == CollegeFilter
                                    select department.DepartmentName);

                FilteredDepartments = await departments.ToListAsync();
            }

            if (!string.IsNullOrWhiteSpace(DepartmentFilter))
            {
                query = query.Where(dept => dept.DepartmentName == DepartmentFilter);
            }

            Users = await query.ToListAsync<dynamic>();
        }


        public async Task<IActionResult> OnPostAddToCommittee(int userId, string fName, string lName)
        {
            var user = await _context.User.FindAsync(userId);

            Committee.GrantType = "ARCC";
            Committee.UserId = userId;
            Committee.FirstName = fName;
            Committee.LastName = lName;

            _context.Committee.Add(Committee);

            await _context.SaveChangesAsync();


            if (user != null) {


                user.CommitteeId = Committee.Id;
                user.Committee = "ARCC";

                await _context.SaveChangesAsync();

            }
 

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveFromCommittee(int userId)
        {
            var user = await _context.User.FindAsync(userId);
            var committeeUser = await _context.Committee.FindAsync(userId);

            if (committeeUser != null)
            {
                _context.Committee.Remove(committeeUser);
                await _context.SaveChangesAsync(); 
            }

            if (user != null)
            {

                user.CommitteeId = null;
                user.Committee = null;
                await _context.SaveChangesAsync();

            }

            return RedirectToPage();

        }
    }
}

Capstone/CS4760_Project/Pages/Admin/OUR_Reviewers.cshtml.cs
using CS4760_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using CS4760_Project.Data;
using NuGet.Versioning;
using Microsoft.IdentityModel.Tokens;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;


namespace CS4760_Project.Pages.Admin
{
    public class OUR_ReviewersModel : PageModel
    {
        private CS4760_Project.Data.CS4760_ProjectContext _context;
        public OUR_ReviewersModel(CS4760_Project.Data.CS4760_ProjectContext context)
        {
            _context = context;
        }
        public User AuthenticatedUser { get; set; }
        public IList<User> User { get; set; } = default!;
        public IList<College> Colleges { get; set; } = default!;

        public IList<Department> Departments { get; set; } = default!;

        public IList<Models.Committee> Committees { get; set; } = default!;
        public List<dynamic> Users { get; set; } = new List<dynamic>();

        [BindProperty(SupportsGet = true)]
        public string FirstNameFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string LastNameFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string CollegeFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string DepartmentFilter { get; set; }

        [BindProperty]
        public Models.Committee Committee { get; set; }

        public IList<string> FilteredDepartments { get; set; } = new List<string>();
        public async Task OnGetAsync()
        {
            if (HttpContext.Session.GetString("UserData") != null)
            {
                AuthenticatedUser = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("UserData"));
            }

            Colleges = await _context.College.ToListAsync();

            var query = (from user in _context.User
                         join college in _context.College on user.CollegeId equals college.CollegeId
                         join department in _context.Department on user.DepartmentId equals department.DepartmentId
                         select new
                         {
                             IsAdmin = user.IsAdmin,
                             CommitteeId = user.CommitteeId,
                             Id = user.Id,
                             FirstName = user.FirstName,
                             LastName = user.LastName,
                             CollegeName = college.CollegeName,
                             DepartmentName = department.DepartmentName,
                             Committee = user.Committee,

                         });

            // Query Filters

            if (!string.IsNullOrWhiteSpace(FirstNameFilter))
            {
                query = query.Where(user => user.FirstName == FirstNameFilter);
            }

            if (!string.IsNullOrWhiteSpace(LastNameFilter))
            {
                query = query.Where(user => user.LastName == LastNameFilter);
            }

            if (!string.IsNullOrWhiteSpace(CollegeFilter))
            {
                query = query.Where(college => college.CollegeName == CollegeFilter);
                var departments = (from department in _context.Department
                                   where department.College == CollegeFilter
                                   select department.DepartmentName);

                FilteredDepartments = await departments.ToListAsync();
            }

            if (!string.IsNullOrWhiteSpace(DepartmentFilter))
            {
                query = query.Where(dept => dept.DepartmentName == DepartmentFilter);
            }

            Users = await query.ToListAsync<dynamic>();


        }

        public async Task<IActionResult> OnPostAddToCommittee(int userId, string fName, string lName)
        {
            var user = await _context.User.FindAsync(userId);


            Committee.GrantType = "OUR";
            Committee.UserId = userId;
            Committee.FirstName = fName;
            Committee.LastName = lName;

            _context.Committee.Add(Committee);

            await _context.SaveChangesAsync();


            if (user != null)
            {


                user.CommitteeId = Committee.Id;
                user.Committee = "OUR";

                await _context.SaveChangesAsync();

            }


            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveFromCommittee(int userId)
        {
            var user = await _context.User.FindAsync(userId);
            var committeeUser = await _context.Committee.FindAsync(userId);

            if (committeeUser != null)
            {
                _context.Committee.Remove(committeeUser);
                await _context.SaveChangesAsync();
            }

            if (user != null)
            {

                user.CommitteeId = null;
                user.Committee = null;
                await _context.SaveChangesAsync();

            }

            return RedirectToPage();

        }
    }
}

Capstone/CS4760_Project/Pages/Admin/RSPG_Reviewers.cshtml.cs
using CS4760_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using CS4760_Project.Data;
using NuGet.Versioning;
using Microsoft.IdentityModel.Tokens;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;


namespace CS4760_Project.Pages.Admin
{
    public class RSPG_ReviewersModel : PageModel
    {
        private CS4760_Project.Data.CS4760_ProjectContext _context;
        public RSPG_ReviewersModel(CS4760_Project.Data.CS4760_ProjectContext context)
        {
            _context = context;
        }
        public User AuthenticatedUser { get; set; }
        public IList<User> User { get; set; } = default!;
        public IList<College> Colleges { get; set; } = default!;

        public IList<Department> Departments { get; set; } = default!;

        public IList<Models.Committee> Committees { get; set; } = default!;
        public List<dynamic> Users { get; set; } = new List<dynamic>();

        [BindProperty(SupportsGet = true)]
        public string FirstNameFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string LastNameFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string CollegeFilter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string DepartmentFilter { get; set; }

        [BindProperty]
        public Models.Committee Committee { get; set; }

        public IList<string> FilteredDepartments { get; set; } = new List<string>();
        public async Task OnGetAsync()
        {
            if (HttpContext.Session.GetString("UserData") != null)
            {
                AuthenticatedUser = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("UserData"));
            } 

            Colleges = await _context.College.ToListAsync();

            var query = (from user in _context.User
                         join college in _context.College on user.CollegeId equals college.CollegeId
                         join department in _context.Department on user.DepartmentId equals department.DepartmentId
                         select new
                         {
                             IsAdmin = user.IsAdmin,
                             CommitteeId = user.CommitteeId,
                             Id = user.Id,
                             FirstName = user.FirstName,
                             LastName = user.LastName,
                             CollegeName = college.CollegeName,
                             DepartmentName = department.DepartmentName,
                             Committee = user.Committee,

                         });

            // Query Filters

            if (!string.IsNullOrWhiteSpace(FirstNameFilter))
            {
                query = query.Where(user => user.FirstName == FirstNameFilter);
            }

            if (!string.IsNullOrWhiteSpace(LastNameFilter))
            {
                query = query.Where(user => user.LastName == LastNameFilter);
            }

            if (!string.IsNullOrWhiteSpace(CollegeFilter))
            {
                query = query.Where(college => college.CollegeName == CollegeFilter);
                var departments = (from department in _context.Department
                                   where department.College == CollegeFilter
                                   select department.DepartmentName);

                FilteredDepartments = await departments.ToListAsync();
            }

            if (!string.IsNullOrWhiteSpace(DepartmentFilter))
            {
                query = query.Where(dept => dept.DepartmentName == DepartmentFilter);
            }

            Users = await query.ToListAsync<dynamic>();


        }

        public async Task<IActionResult> OnPostAddToCommittee(int userId, string fName, string lName)
        {
            var user = await _context.User.FindAsync(userId);


            Committee.GrantType = "RSPG";
            Committee.UserId = userId;
            Committee.FirstName = fName;
            Committee.LastName = lName;

            _context.Committee.Add(Committee);

            await _context.SaveChangesAsync();


            if (user != null)
            {


                user.CommitteeId = Committee.Id;
                user.Committee = "RSPG";

                await _context.SaveChangesAsync();

            }


            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveFromCommittee(int userId)
        {
            var user = await _context.User.FindAsync(userId);
            var committeeUser = await _context.Committee.FindAsync(userId);

            if (committeeUser != null)
            {
                _context.Committee.Remove(committeeUser);
                await _context.SaveChangesAsync();
            }

            if (user != null)
            {

                user.CommitteeId = null;
                user.Committee = null;
                await _context.SaveChangesAsync();

            }

            return RedirectToPage();

        }
    }
}

Capstone/CS4760_Project/Pages/Admin/ARCC_Reviewers.cshtml
@page
@model CS4760_Project.Pages.Admin.ARCC_ReviewersModel
@{
    ViewData["Title"] = "ARCC Committee";

}
<table class="table">
    <caption>ARCC Committee Members</caption>
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">College</th>
            <th scope="col">Department</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @if(Model.Users != null && Model.Users.Any())
        {
            @foreach (var item in Model.Users)
            {
                @if (item.Committee == "ARCC")
                {
                    <tr>
                        <td>
                            @item.FirstName
                        </td>
                        <td>
                            @item.LastName
                        </td>
                        <td>
                            @item.CollegeName
                        </td>
                        <td>
                            @item.DepartmentName
                        </td>
                        <td>
                            <form method="post" asp-page-handler="RemoveFromCommittee" style="display:inline">
                                <input type="hidden" name="userId" value="@item.Id" />
                              
                                <button type="submit" class="btn redButton">Remove</button>

                            </form>

                        </td>
                    </tr>
                }

            }  
        }

    </tbody>
</table>

<hr />
<div class="mb-4"></div>


<div class="container">
    <form method="get" id="filterForm">
        <label asp-for="FirstNameFilter">First Name</label>
        <input asp-for="FirstNameFilter" />
        <label asp-for="LastNameFilter">Last Name</label>
        <input asp-for="LastNameFilter" />
        <label asp-for="CollegeFilter">College</label>
        <select asp-for="CollegeFilter" id="colleges" onchange="submitForm()">
            <option value="" selected></option>
            @if (Model.Colleges != null)
            {
                @foreach (var item in Model.Colleges)
                {
                    <option value="@item.CollegeName">@item.CollegeName</option>
                }

            }
            else
            {
                <option>No Colleges Available</option>
            }
           
        </select>
        <label asp-for="DepartmentFilter">Department</label>
        <select asp-for="DepartmentFilter">
            <option value="" selected></option>
            @foreach (var department in Model.FilteredDepartments)
            {
                <option value="@department">@department</option>
            }
           
        </select>
        <button type="submit" class="btn purpleButton" style="border:none">Filter</button>

    </form>
</div>

<script>
    const submitForm = () => {
        document.getElementById("filterForm").submit();
    }
</script>


<table class="table">
    <caption>Users</caption>
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">College</th>
            <th scope="col">Department</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
       @*  @if (Model.User != null && Model.User.Any())
        { *@
            @foreach (var item in Model.Users)
            {
                @if (item.IsAdmin || item.CommitteeId != null)
                {
                    continue;
                }
                <tr>
                    <td>
                        @item.FirstName
                    </td>
                    <td>
                        @item.LastName
                    </td>
                    <td>
                        @item.CollegeName
                    </td>
                    <td>
                        @item.DepartmentName
                    </td>
                    <td>
                        <form method="post" asp-page-handler="AddToCommittee" style="display:inline">
                            <input type="hidden" name="userId" value="@item.Id" />
                            <input type="hidden" name="fName" value="@item.FirstName" />
                            <input type="hidden" name="lName" value="@item.LastName" />
                            <button type="submit" class="btn purpleButton" style="border:none">Add</button>

                        </form>

                    </td>

                </tr>
            }
            
        @* } *@
       
    </tbody>
</table>

Capstone/CS4760_Project/Pages/Admin/OUR_Reviewers.cshtml
@page
@model CS4760_Project.Pages.Admin.OUR_ReviewersModel
@{
    ViewData["Title"] = "OUR Committee";

}
<table class="table">
    <caption>OUR Committee Members</caption>
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">College</th>
            <th scope="col">Department</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Users != null && Model.Users.Any())
        {
            @foreach (var item in Model.Users)
            {
                @if (item.Committee == "OUR")
                {
                    <tr>
                        <td>
                            @item.FirstName
                        </td>
                        <td>
                            @item.LastName
                        </td>
                        <td>
                            @item.CollegeName
                        </td>
                        <td>
                            @item.DepartmentName
                        </td>
                        <td>
                            <form method="post" asp-page-handler="RemoveFromCommittee" style="display:inline">
                                <input type="hidden" name="userId" value="@item.Id" />

                                <button type="submit" class="btn redButton" style="border:none">Remove</button>

                            </form>

                        </td>
                    </tr>
                }

            }
        }

    </tbody>
</table>

<hr />
<div class="mb-4"></div>


<div class="container">
    <form method="get" id="filterForm">
        <label asp-for="FirstNameFilter">First Name</label>
        <input asp-for="FirstNameFilter" />
        <label asp-for="LastNameFilter">Last Name</label>
        <input asp-for="LastNameFilter" />
        <label asp-for="CollegeFilter">College</label>
        <select asp-for="CollegeFilter" id="colleges" onchange="submitForm()">
            <option value="" selected></option>
            @if (Model.Colleges != null)
            {
                @foreach (var item in Model.Colleges)
                {
                    <option value="@item.CollegeName">@item.CollegeName</option>
                }

            }
            else
            {
                <option>No Colleges Available</option>
            }

        </select>
        <label asp-for="DepartmentFilter">Department</label>
        <select asp-for="DepartmentFilter">
            <option value="" selected></option>
            @foreach (var department in Model.FilteredDepartments)
            {
                <option value="@department">@department</option>
            }

        </select>
        <button type="submit" class="btn purpleButton" style="border:none">Filter</button>

    </form>
</div>

<script>
    const submitForm = () => {
        document.getElementById("filterForm").submit();
    }
</script>


<table class="table">
    <caption>Users</caption>
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">College</th>
            <th scope="col">Department</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @*  @if (Model.User != null && Model.User.Any())
        { *@
        @foreach (var item in Model.Users)
        {
            @if (item.IsAdmin || item.CommitteeId != null)
            {
                continue;
            }
            <tr>
                <td>
                    @item.FirstName
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.CollegeName
                </td>
                <td>
                    @item.DepartmentName
                </td>
                <td>
                    <form method="post" asp-page-handler="AddToCommittee" style="display:inline">
                        <input type="hidden" name="userId" value="@item.Id" />
                        <input type="hidden" name="fName" value="@item.FirstName" />
                        <input type="hidden" name="lName" value="@item.LastName" />

                        <button type="submit" class="btn purpleButton" style="border:none">Add</button>

                    </form>

                </td>

            </tr>
        }

        @* } *@

    </tbody>
</table>


Capstone/CS4760_Project/Pages/Admin/RSPG_Reviewers.cshtml
@page
@model CS4760_Project.Pages.Admin.RSPG_ReviewersModel
@{
    ViewData["Title"] = "RSPG Committee";

}
<table class="table">
    <caption>RSPG Committee Members</caption>
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">College</th>
            <th scope="col">Department</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Users != null && Model.Users.Any())
        {
            @foreach (var item in Model.Users)
            {
                @if (item.Committee == "RSPG")
                {
                    <tr>
                        <td>
                            @item.FirstName
                        </td>
                        <td>
                            @item.LastName
                        </td>
                        <td>
                            @item.CollegeName
                        </td>
                        <td>
                            @item.DepartmentName
                        </td>
                        <td>
                            <form method="post" asp-page-handler="RemoveFromCommittee" style="display:inline">
                                <input type="hidden" name="userId" value="@item.Id" />
                                <button type="submit" class="btn redButton" style="border:none">Remove</button>

                            </form>

                        </td>
                    </tr>
                }

            }
        }

    </tbody>
</table>

<hr />
<div class="mb-4"></div>


<div class="container">
    <form method="get" id="filterForm">
        <div>
            <label asp-for="FirstNameFilter">First Name</label>
            <input asp-for="FirstNameFilter" />
            <label asp-for="LastNameFilter">Last Name</label>
            <input asp-for="LastNameFilter" />
            <p></p>
        </div>
        <div>
            <label asp-for="CollegeFilter">College</label>
            <select asp-for="CollegeFilter" id="colleges" onchange="submitForm()">
                <option value="" selected></option>
                @if (Model.Colleges != null)
                {
                    @foreach (var item in Model.Colleges)
                    {
                        <option value="@item.CollegeName">@item.CollegeName</option>
                    }

                }
                else
                {
                    <option>No Colleges Available</option>
                }

            </select>
            <label asp-for="DepartmentFilter">Department</label>
            <select asp-for="DepartmentFilter">
                <option value="" selected></option>
                @foreach (var department in Model.FilteredDepartments)
                {
                    <option value="@department">@department</option>
                }

            </select>
            <p></p>
        </div>
        <button type="submit" class="btn purpleButton" style="border:none">Filter</button>
    </form>
</div>

<script>
    const submitForm = () => {
        document.getElementById("filterForm").submit();
    }
</script>


<table class="table">
    <caption>Users</caption>
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">College</th>
            <th scope="col">Department</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @*  @if (Model.User != null && Model.User.Any())
        { *@
        @foreach (var item in Model.Users)
        {
            @if (item.IsAdmin || item.CommitteeId != null)
            {
                continue;
            }
            <tr>
                <td>
                    @item.FirstName
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.CollegeName
                </td>
                <td>
                    @item.DepartmentName
                </td>
                <td>
                    <form method="post" asp-page-handler="AddToCommittee" style="display:inline">
                        <input type="hidden" name="userId" value="@item.Id" />
                        <input type="hidden" name="fName" value="@item.FirstName" />
                        <input type="hidden" name="lName" value="@item.LastName" />
                        <button type="submit" class="btn purpleButton" style="border:none">Add</button>

                    </form>

                </td>

            </tr>
        }

        @* } *@

    </tbody>
</table>